<?php

namespace app\widgets;

use yii\base\Widget;

class SidebarWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('sidebar');
    }
}