<?php

namespace app\widgets;

use yii\base\Widget;
use yii\helpers\Html;

class TopNavWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('top_nav');
    }
}